include 'Pages.inc'
include '../Includes/DrawFuncsInclude.asm'

include '_components/FontStyle.asm'
include '_components/MainPage.asm'
include '_components/GamePage.asm'
include '_components/AboutPage.asm'
include '_components/SettingsPage.asm'
include '_components/DefaultLayout.asm'
include '_components/LoadingPage.asm'
include '_components/PausePage.asm'
include '_components/WinnerPage.asm'
include '_components/HotkeysPage.asm'
include '_components/ExitPage.asm'
include '_components/LoggingPage.asm'
include '_components/LeadBoardPage.asm'
include 'Page.asm'