struct Ticks 
    counter     dd          ?
    t1          Circle      ?
    t2          Circle      ?
    t3          Circle      ?
    t4          Circle      ?
    t5          Circle      ?
    t6          Circle      ?
    t7          Circle      ?
    t9          Circle      ?
    t8          Circle      ?
    t10         Circle      ?
    t11         Circle      ?
    t12         Circle      ?
    t13         Circle      ?
    t14         Circle      ?
    t15         Circle      ?
    t16         Circle      ?
    t17         Circle      ?
    t18         Circle      ?
    t19         Circle      ?
    t20         Circle      ?
    t21         Circle      ?
    t22         Circle      ?
    t23         Circle      ?
    t24         Circle      ?
    t25         Circle      ?
    t26         Circle      ?
    t27         Circle      ?
    t28         Circle      ?
    t29         Circle      ?
    t30         Circle      ?
    t31         Circle      ?
    t32         Circle      ?
    t33         Circle      ? 
ends

struct TicksFont
    counter     dd          ?
    t1          Circle      ?
    t2          Circle      ?
    t3          Circle      ?
    t4          Circle      ?
    t5          Circle      ?
    t6          Circle      ?
    t7          Circle      ?
    t9          Circle      ?
    t8          Circle      ?
    t10         Circle      ?
    t11         Circle      ?
    t12         Circle      ?
    t13         Circle      ?
    t14         Circle      ?
    t15         Circle      ?
    t16         Circle      ?
    t17         Circle      ?
    t18         Circle      ?
    t19         Circle      ?
    t20         Circle      ?
    t21         Circle      ?
    t22         Circle      ?
    t23         Circle      ?
    t24         Circle      ?
    t25         Circle      ?
    t26         Circle      ?
    t27         Circle      ?
    t28         Circle      ?
    t29         Circle      ?
    t30         Circle      ?
    t31         Circle      ?
    t32         Circle      ?
    t33         Circle      ? 
    t34         Circle      ?
ends

TicksList           Ticks       ? ; 33

TicksFontList_Radiuses  dd      17, 13         
TicksFontList_Float_c1  TicksFont   ?
TicksFontList_Float_c2  TicksFont   ?
TicksFontList_Float     dd      2,\
                                TicksFontList_Float_c1, TicksFontList_Float_c2
TicksFontList_Centers   dd      34,\ ; 34
                                957, 450,\ ; center 1
                                123, 450,\ ; center 2
                                957, 450,\ ; center 3
                                957, 450,\ ; center 4
                                957, 450,\ ; center 5
                                957, 450,\ ; center 6
                                957, 450,\ ; center 7
                                957, 450,\ ; center 8
                                957, 450,\ ; center 9
                                957, 450,\ ; center 10
                                957, 450,\ ; center 11
                                957, 450,\ ; center 12
                                957, 450,\ ; center 13
                                957, 450,\ ; center 14
                                957, 450,\ ; center 15
                                957, 450,\ ; center 16
                                957, 450,\ ; center 17
                                957, 450,\ ; center 18
                                957, 450,\ ; center 19
                                957, 450,\ ; center 20
                                957, 450,\ ; center 21
                                957, 450,\ ; center 22
                                957, 450,\ ; center 23
                                957, 450,\ ; center 24
                                957, 450,\ ; center 25
                                957, 450,\ ; center 26
                                957, 450,\ ; center 27
                                957, 450,\ ; center 28
                                957, 450,\ ; center 29
                                957, 450,\ ; center 30
                                957, 450,\ ; center 31
                                957, 450,\ ; center 32
                                957, 450,\ ; center 33
                                957, 450   ; center 34