struct Tick
    c1   Circle   ?
    c2   Circle   ?
    c3   Circle   ?
    c4   Circle   ?
    c5   Circle   ?

    
ends

struct TickFont
    c1   Circle   ?
    c2   Circle   ?
ends

struct Ticks 
    t1   Tick     ?
    t2   Tick     ?
    t3   Tick     ?
    t4   Tick     ?
    t5   Tick     ?
    t6   Tick     ?
    t7   Tick     ?
    t8   Tick     ?
    t9   Tick     ?
    t10  Tick     ?
    t11  Tick     ?
    t12  Tick     ?
    t13  Tick     ?
    t14  Tick     ?
    t15  Tick     ?
    t16  Tick     ?
    t17  Tick     ?
    t18  Tick     ?
    t19  Tick     ?
    t20  Tick     ?
    t21  Tick     ?
    t22  Tick     ?
    t23  Tick     ?
    t24  Tick     ?
    t25  Tick     ?
    t26  Tick     ?
    t27  Tick     ?
    t28  Tick     ?
    t29  Tick     ?
    t30  Tick     ?
    t31  Tick     ?
    t32  Tick     ?
    t33  Tick     ?
ends

struct TicksFont
    tick    Ticks   ?
    tCenter Tick    ?
ends

TicksList     Ticks         ? ; 33
TicksFontList TicksFont     ? ; 34
