; data
FS_Curent       dd      ?

; Font Sizes
FS_Headline     =       79
FS_Button       =       50
FS_Title        =       40
FS_Info         =       20
FS_Cost         =       18
FS_WtrMark      =       10
FS_Base         =       20

; EN Letters

; RU Letters
; А
Ltr_RU_A        dd      3,\
                        6,  0,  9,  0,  3, 28, 0, 28,\  ; /
                        3, 18,  3, 22, 12, 22, 12, 18,\ ; -
                        6,  0,  9,  0, 15, 28, 12, 28   ; \

; Б
; В
; Г
; Д
; Е
; Ё
; Ж
; З
; И
; Й
; К
; Л
; М
; Н
; О
; П
; Р
; С
; Т
; У
; Ф
; Х
; Ц
; Ч
; Ш
; Щ
; Ъ
; Ы
; Ь
; Э
; Ю
; Я

