name: Build and Upload Artifacts

on:
    pull_request:
      branches:
        - master

env:
  SOURCE_FILE: test.asm
  OUTPUT: output.exe

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fasm-version: [1.71, 1.72, 1.73]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fasm

      - name: Build .exe file
        run: |
          fasm ${{ env.SOURCE_FILE }} ${{ env.OUTPUT }}
          
      - name: Save *.exe files
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ${{ env.OUTPUT }}
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download *.exe build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./artifacts/exe

      - name: Upload .bin file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-file
          path: |
            ./artifacts/exe/${{ env.OUTPUT }}