name: dev-build
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install FASM
        uses: stevenwdv/setup-fasm@v1

      - name: Test fasm
        run: fasm main.asm main.exe