name: dev-build
on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install FASMg
        uses: stevenwdv/setup-fasm@v1
        with:
          edition: fasmg
          fasmg-download-packages: true
          fasmg-include-packages: utility,x86

      - name: Test fasm g
        run: fasmg main.asm main.exe