name: prod-build
on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FASM
        uses: stevenwdv/setup-fasm@v1
      
      - name: Build Project
        run: fasm main.asm main.exe