name: release-prod
on:
  push:
    tags:
      - "v*.*.*"
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FASM
        uses: stevenwdv/setup-fasm@v1
      
      - name: Test fasm
        run: fasm main.asm main.exe
  
  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install FASM
        uses: stevenwdv/setup-fasm@v1
      
      - name: Test fasm
        run: fasm main.asm main.exe

      - name: Release Project
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.asm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}