; A
ltr_EN_54       dd       ?
; B
ltr_EN_55       dd       ?
; C
ltr_EN_56       dd       ?
; D
ltr_EN_57       dd       ?
; E
ltr_EN_58       dd       ?
; F
ltr_EN_59       dd       ?
; G
ltr_EN_60       dd       ?
; H
ltr_EN_61       dd       ?
; I
ltr_EN_62       dd       ?
; J 
ltr_EN_63       dd       ?
; K
ltr_EN_64       dd       ?
; L
ltr_EN_65       dd       ?
; M
ltr_EN_66       dd       ?
; N
ltr_EN_67       dd       ?
; O
ltr_EN_68       dd       ?
; P
ltr_EN_69       dd       4, 12,\
                         0,  1,  4,  1,  4, 27,  0, 27,\ ; | (left)
                         1,  0,  1,  4, 11,  4, 11,  0,\ ; - (top)
                         8,  1, 12,  1, 12, 11,  8, 11,\ ; | (right)
                         4,  8,  4, 12, 11, 12, 11,  8   ; - (center)
; Q
ltr_EN_70       dd       ?
; R
ltr_EN_71       dd       5, 14,\
                         0,  1,  4,  1,  4, 27,  0, 27,\ ; | (left)
                         1,  0,  1,  4, 11,  4, 11,  0,\ ; - (top)
                         8,  1, 12,  1, 12, 11,  8, 11,\ ; | (right)
                         4,  8,  4, 12, 11, 12, 11,  8,\ ; - (center)
                         9, 12,  5, 12, 10, 27, 14, 27   ; \ (right-buttom)
; S
ltr_EN_72       dd       5, 14,\
                         0,  1,  4,  1,  4, 13,  0, 13,\ ; | (left)
                         1,  0,  1,  4, 11,  4, 11,  0,\ ; - (top)
                         8, 11, 12, 11, 12, 27,  8, 27,\ ; | (right)
                         4, 11,  4, 15, 11, 15, 11, 11,\ ; - (center)
                         0, 23,  0, 27, 11, 27, 11, 23   ; - (bottom)
; T
ltr_EN_73       dd       ?
; U
ltr_EN_74       dd       ?
; V
ltr_EN_75       dd       ?
; W
ltr_EN_76       dd       ?
; X
ltr_EN_77       dd       ?
; Y
ltr_EN_78       dd       ?
; Z
ltr_EN_79       dd       ?