; ' '
spl_44      dd      -1, 0
; ','
spl_45      dd      ?
; '<-'
spl_46      dd      2, 20,\
                    14,  0, 14,  3,  0, 10,  0,  7,\
                    14, 14, 14, 17,  0, 10,  0,  7
                          ; x from 46 to 61
                          ; y from 1014 to 1032
spl_47      dd      ?
spl_48      dd      ?
spl_49      dd      ?
spl_50      dd      ?
spl_51      dd      ?
spl_52      dd      ?
spl_53      dd      ?